### ISSUE TITLE
Joi version 15

### ISSUE THREAD

**Issue by jscheffner** [wegolook/joi-objectid#15]
The module requires a joi version between 9 and 14. Is there any reason not to use it with joi 15? In my project its seems to work fine, so I could create a PR to update the package.json file accordingly.

**Comment by xingwang** [comment]
We locked it down to the Joi versions we were using at the time. If you create a PR, maybe @breauxna can merge it in for you.

**Comment by breauxna** [comment]
Hey @jscheffner, yeah I'd be happy to merge your PR if you want to go ahead and update the package.json. Thanks!
